変更しました
widesnow-t/Suica pull request #1
Opened 2021-12-10 20:55 UTC by widesnow-t

2021-12-13 00:22 UTC, Arisaarisa commented
現在の状態ですと、商品の金額を１回入力しただけで、お買い物が終了してしまいます😃
スイカの残高を切るまで金額の入力ができるように修正お願いします🙏
お買い物できるかどうかを正偽で判断させてみてください✨

2021-12-14 05:10 UTC, kazu-taka commented on index.php
> +do {
@widesnow-t 
フローチャートを見ると、ループに入る前に以下の処理を実行しています。
![image](https://user-images.githubusercontent.com/5278718/145936721-289ded85-8a76-489f-9c2f-1ce3c287daab.png)

また、ループの処理を見ると、ループの最後で条件を判断しているので、do 〜 whileを使用しているのが判断できます！

![image](https://user-images.githubusercontent.com/5278718/145936790-6c79f04a-9098-452c-b4f0-89faca580f11.png)

上記のことを踏まえて、ループに入る前にやるべきことと、do 〜 whileの中でやるべき事を整理しながら修正お願いします✨
現状だとループ処理が2回入っていますが、1つだけになります😊

2021-12-14 21:27 UTC, kazu-taka requested changes
@widesnow-t 
コメントしたので修正お願いします😊

2021-12-14 21:27 UTC, kazu-taka commented on index.php
> +}
@widesnow-t 
判断するのがageだけであれば、switch使ったほうが分かりやすいので、次回からはswitchを使うようにして下さい✨

2021-12-14 21:27 UTC, kazu-taka commented on index.php
> +};
@widesnow-t 
結果的には問題ないですが、今回はフローチャート通りに作るのが課題なので、買い物フラグを使用するように修正お願いします:bow:
![image](https://user-images.githubusercontent.com/5278718/146081893-8dbdf864-dc2f-4076-8ba4-fa95341df887.png)

2021-12-15 04:20 UTC, kzri4 commented
今のままだと、 以下の修正がまだできてないです。
>買い物フラグを使用するように修正お願いします🙇

変数`$shopping`を新しく用意し、買い物が継続できるならtrueにし、継続ができない場合は`
falseにしてそれを判定して、プログラムが進ませる or 終了させるという形で考えます！

2021-12-15 09:02 UTC, kzri4 reviewed
コメントしましたので修正お願いします😊

2021-12-15 09:02 UTC, zeeero4 commented on index.php
> +if ($shopping > 0) {
フローチャートでは、少しややこしいですが、チャージされた後に、Boolean型で`$shopping = true;`とし$shoppingが `true`である限り、`do 〜 while`内のプログラムが動くようにするという形になり、買い物が継続できない場合に`$shopping = false;`となって、買い物が終了するという形ですので、そのとおりにコードを書いてみてください😊

2021-12-15 09:02 UTC, kzri4 commented on index.php
> +        break;
該当する数字がない場合に`break`だとネストから抜けるだけで、下の処理に進んでしまいますので`exit`でプログラムを強制終了するようにしてください😊

2021-12-15 22:06 UTC, kazu-taka requested changes
@widesnow-t 
確認お願いします✨

2021-12-15 22:06 UTC, kazu-taka commented on index.php
> +$shopping = $sic;
@widesnow-t 
ここはただ再代入をしているだけなので、そのまま$sicを使用してOKです👍

2021-12-15 22:06 UTC, kazu-taka commented on index.php
> +if (($shopping > 0) === true) {
@widesnow-t 
1、2、3以外を入力した場合は、上のところでexitしているので、ここは確実に0より大きい値が入ってきていると想定してプログラムを書いて良いので、ここのifは不要です😊

2021-12-16 04:46 UTC, Arisaarisa commented
5000円チャージした時に終了してしまうので修正お願いします🙏

2021-12-16 10:15 UTC, Arisaarisa commented
![LGTM](https://image.lgtmoon.dev/150621)

2021-12-16 10:31 UTC, merged